language: python

python:
  - 3.5
  - 3.6

services: postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

branches:
  only:
  - master
  - v3

install:
  - pip install tox-travis

script:
  - tox

env:
  - TOXENV=django110
  - TOXENV=django111
  - TOXENV=coverage

notifications:
  email: false