language: python

python:
  - 3.5
  - 3.6

services: postgresql

addons:
  postgresql: "9.4"

before_script:
  - sudo psql -c "CREATE DATABASE mydb;" -U postgres
  - sudo psql -c "CREATE USER akshay WITH PASSWORD 'bar';" -U postgres
  - sudo psql -c "ALTER USER akshay CREATEDB;" -U postgres

branches:
  only:
  - master
  - v3

install:
  - pip install tox-travis

script:
  - tox

sudo: required

env:
  - TOXENV=django110
  - TOXENV=django111
  - TOXENV=coverage
  - BOTO_CONFIG=/tmp/nowhere

notifications:
  email: false