language: python

python:
  - 3.5
  - 3.6
  - 3.7

services: postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_script:
  - sudo psql -c "CREATE DATABASE mydb;" -U postgres
  - sudo psql -c "CREATE USER gollahalli WITH PASSWORD 'bar';" -U postgres
  - sudo psql -c "ALTER USER gollahalli CREATEDB;" -U postgres

branches:
  only:
  - master
  - v3

install:
  - pip install tox-travis

script:
  - tox

sudo: required

env:
  - TOXENV=django2
  - TOXENV=coverage
  global:
    - PGPORT=5433

notifications:
  email:
    on_failure: change